baseURL = 'https://labs.shukebeta.com/'
languageCode = 'en-us'
title = 'SHUKE Labs Ltd'

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableXML = false
  minifyOutput = true
